# Assignment 2

## Naïve Bayes and Logistic Regression

# ***Question 1***

## Answer 1.1

In [35]:


import numpy as np
import pandas as pd
from sklearn.datasets import load_iris
from sklearn import metrics
from sklearn.naive_bayes import GaussianNB

# Now we load the Iris DataSet in a variable called "iris"
iris = load_iris()

# inpsect iris_dataset keys
print ()
print ("Iris Dataset Keys:")
print (iris.keys())

# X is original data, Rows are individual samples, colums are features
X = iris.data

# class lable (integer)
# corresponds to index of row of X
y = iris.target

# inspect target names
print ()
print ("Class Labels are:")
print (iris.target_names)

# number of class labels
Cn = len(iris.target_names)
print ("{} class labels".format(Cn))

print (X.shape)
print (y.shape)

x2 = pd.DataFrame(iris.data, columns = iris.feature_names)
y2 = pd.DataFrame(iris.target_names)
x1 = x2.head()
y1 = y2.head()
print ()
print ("X values will be extracted as:")
print (x1)

print()
print("Y values will be extracted as:")
print (y1)


Iris Dataset Keys:
dict_keys(['data', 'target', 'target_names', 'DESCR', 'feature_names', 'filename'])

Class Labels are:
['setosa' 'versicolor' 'virginica']
3 class labels
(150, 4)
(150,)

X values will be extracted as:
   sepal length (cm)  sepal width (cm)  petal length (cm)  petal width (cm)
0                5.1               3.5                1.4               0.2
1                4.9               3.0                1.4               0.2
2                4.7               3.2                1.3               0.2
3                4.6               3.1                1.5               0.2
4                5.0               3.6                1.4               0.2

Y values will be extracted as:
            0
0      setosa
1  versicolor
2   virginica


# Answer 1.2 and 1.3

In [37]:
from sklearn.model_selection import train_test_split
X_train,X_test,y_train,y_test=train_test_split(X,y,test_size=0.3,random_state=6)
      
from sklearn.naive_bayes import GaussianNB
gb = GaussianNB()
      
gb.fit(X_train,y_train)
      

from sklearn.metrics import accuracy_score
y_pred = nv.predict(X_test)

from sklearn.metrics import confusion_matrix
confusion_matrix(y_pred,y_test)

from sklearn.metrics import classification_report
print(classification_report(y_pred,y_test))

print()
print("accuracy score as per classification report from sklearn metrics is:")
print(accuracy_score(y_pred,y_test))

print()
print("Confusion matrix as derived from sklearn metrics is:")
print(confusion_matrix(y_pred,y_test))


# Now we will validate our results by calculating correct predictions and false predictions

conf = confusion_matrix(y_test, y_pred)

a = conf.shape
corrPred = 0
falsePred = 0

for row in range(a[0]):
    for c in range(a[1]):
        if row == c:
            corrPred +=conf[row,c]
        else:
            falsePred += conf[row,c]
print('Correct predictions: ', corrPred)
print('False predictions', falsePred)
print ('\n\nAccuracy of the Naive Bayes Clasification is: ', corrPred/(conf.sum()))

              precision    recall  f1-score   support

           0       1.00      1.00      1.00        15
           1       1.00      0.83      0.91        18
           2       0.80      1.00      0.89        12

    accuracy                           0.93        45
   macro avg       0.93      0.94      0.93        45
weighted avg       0.95      0.93      0.93        45


accuracy score as per classification report from sklearn metrics is:
0.9333333333333333

Confusion matrix as derived from sklearn metrics is:
[[15  0  0]
 [ 0 15  3]
 [ 0  0 12]]
Correct predictions:  42
False predictions 3


Accuracy of the Naive Bayes Clasification is:  0.9333333333333333


#### Based on the 3x3 confusion matrix in our case, the columns are the predictions and the rows must therefore be the actual values. The main diagonal (15, 15, 12) gives the correct predictions. That is, the cases where the actual values and the model predictions are the same and rest are false predictions.

#### Accuracy is defined by "Correct Predictions/Total Predictions" and hence our accuracy is coming out to be 93.3334%


### Now we will do some predictions as shown below, which proves the accuracy of our model:

In [38]:
# Predicting the Test set results
print()
z_pred = nv.predict(X_test)
print (iris.target_names[z_pred])


['setosa' 'virginica' 'setosa' 'setosa' 'virginica' 'versicolor'
 'versicolor' 'setosa' 'virginica' 'versicolor' 'virginica' 'versicolor'
 'virginica' 'virginica' 'versicolor' 'versicolor' 'virginica'
 'versicolor' 'versicolor' 'setosa' 'setosa' 'virginica' 'setosa' 'setosa'
 'versicolor' 'versicolor' 'versicolor' 'virginica' 'setosa' 'versicolor'
 'setosa' 'versicolor' 'setosa' 'setosa' 'versicolor' 'virginica'
 'versicolor' 'virginica' 'versicolor' 'setosa' 'setosa' 'virginica'
 'versicolor' 'versicolor' 'setosa']


# ***Question 2***

# Answer 2.1 and 2.2

### Objective: We have to import the car.data dataset from https://archive.ics.uci.edu/ml/machine-learning-databases/car/ and extract X as all columns except the last column and Y as last column.

In [ ]:
import numpy as np
import pandas as pd
import matplotlib.pyplot as plt
import seaborn as sns

data = pd.read_csv('https://archive.ics.uci.edu/ml/machine-learning-databases/car/car.data', header=None)
data.head()

In [ ]:
data.describe()

In [ ]:
print("Shape of the Data: ", data.shape )

In [ ]:
# Assigning names to the columns in the dataset

data.columns = ['Price', 'Maintenance Cost', 'Number of Doors', 'Capacity', 'Size of Luggage Boot', 'safety', 'Decision']

In [ ]:
data.describe()

In [ ]:
# Now we will extract X as all columns except the last column and Y as last column as represented below
# We will validate their shapes and print the values of X and y for our reference in next cell.

# X is the dataframe containing input data / features
# y is the series which has results which are to be predicted.

X=data[data.columns[:-1]]

y=data['Decision']

print("Shape of X: ", X.shape)
print("Shape of y: ", y.shape)

## We will perform EDA to analyze the data now

In [ ]:
data.sample(5)

In [ ]:
#Get info of dataset and check for null values if any
data.info()

In [ ]:
data.columns

In [ ]:
data['Decision'].value_counts().sort_index()

In [ ]:
#As all the columns are categorical, check for unique values of each column

for i in data.columns:
    print(data[i].unique(),"\t",data[i].nunique())

In [ ]:
# Now we will check how these unique categories are distributed among the columns
for i in data.columns:
    print(data[i].value_counts())
    print()

In [ ]:
# From above output, it is clear that all the columns except 'Decision' are distributed equally among data.

#Below is the graph which gives the count of unique values in column.

sns.countplot(data['Decision'])

# It can be seen from the graph that the result 'class' is unbalanced with larger values of 'unacc'.
# So, this is an unbalanced multiclass classification problem.

In [ ]:
# As scikit-learn algorithms do not generally work with string values,
# I've converted string categories to integers.

from sklearn.preprocessing import LabelEncoder

In [ ]:
le=LabelEncoder()

In [ ]:
for i in data.columns:
    data[i]=le.fit_transform(data[i])

In [ ]:
data.head()

In [ ]:
# Now we will get Heatmap of the columns on dataset with each other.
# It shows Pearson's correlation coefficient of column w.r.t other columns. 
fig=plt.figure(figsize=(10,6))
sns.heatmap(data.corr(),annot=True)

#### Ignoring the diagonal values, it can be seen that most of the columns shows very weak correlation with 'Decison'.
#### 'persons' column is showning a weak relation with 'Decision'. Other columns except 'Decision' shows no correlation with each other.

#### So, plotting these columns with each other or doing any analysis on them may not give any productive output.

# Answer 2.3, 2.4 and 2.5

### Objective 2.3 - Split the data into training set and testing set. Perform 10-fold cross validation.
### Objective 2.4 - Train a Logistic regression model for the dataset and explain the parameters of model. 
### Objective 2.5 - Compute the accuracy and confusion matrix. 


In [ ]:
# Divide data in train and test sets


X=data[data.columns[:-1]]

y=data['Decision']

print("Shape of X: ", X.shape)
print("Shape of y: ", y.shape)

from sklearn.model_selection import train_test_split
X_train, X_test, y_train, y_test = train_test_split(X, y, test_size=0.3, random_state=42)

print("Shape of x_train: ", X_train.shape)
print("Shape of y_train: ", y_train.shape)
print("shape of x_test: ", X_test.shape)
print("shape of y_test: ", y_test.shape)

In [ ]:
from sklearn.linear_model import LogisticRegression
from sklearn.metrics import confusion_matrix
from sklearn.model_selection import train_test_split,cross_val_score
from sklearn.metrics import classification_report, confusion_matrix
from sklearn.model_selection import GridSearchCV

In [ ]:
logreg=LogisticRegression(solver='newton-cg',multi_class='multinomial')

In [ ]:
logreg.fit(X_train,y_train)

In [ ]:
logreg.score(X_test,y_test)

In [ ]:
print("Training Accuracy: ",logreg.score(X_train, y_train))
print("Testing Accuracy: ", logreg.score(X_test, y_test))

# predicting the values for x-test
y_pred = logreg.predict(X_test)

# printing the confusion Matrix
cm = confusion_matrix(y_test, y_pred)
print(cm)


In [ ]:
# So, basic logistic regression model is giving very less accuracy. Let's check the learning curves

from sklearn.model_selection import learning_curve,cross_val_score,validation_curve

In [ ]:
lc=learning_curve(logreg,X_train,y_train,cv=10,n_jobs=-1)
size=lc[0]
train_score=[lc[1][i].mean() for i in range (0,5)]
test_score=[lc[2][i].mean() for i in range (0,5)]
fig=plt.figure(figsize=(12,8))
plt.plot(size,train_score)
plt.plot(size,test_score)

# From above graph, with the increasing number of samples, train accuracy is decreasing.

# Let's modify parameters

In [ ]:
from sklearn.model_selection import learning_curve,cross_val_score,validation_curve
param_range=[0.0001,0.001,0.1,1]
curve=validation_curve(logreg,X_train,y_train,cv=5,param_name='C',
    param_range=param_range,n_jobs=-1,)

n=len(param_range)
train_score=[curve[0][i].mean() for i in range (0,n)]
test_score=[curve[1][i].mean() for i in range (0,n)]
fig=plt.figure(figsize=(8,6))
plt.plot(param_range,train_score)
plt.plot(param_range,test_score)
plt.xticks=param_range

#### It clear that C=0.1 is giving a good result.

#### Now, as it is a multiclass classification, I tired using 'newton-cg','sag','lgfbs' solvers.

#### As this dataset is smaller, we can use GridSearch to get best possible parameters

In [ ]:
## As directed in question, we will use 10-fold cross validation

param_grid={'C':[0.01,0.1,1,10],
           'solver':['newton-cg', 'lbfgs', 'sag'],
           'multi_class':['multinomial']}
grid=GridSearchCV(estimator=LogisticRegression(n_jobs=-1),param_grid=param_grid,cv=10,n_jobs=-1)

In [ ]:
grid.fit(X_train,y_train)

In [ ]:
print(grid.best_params_)
print(grid.best_score_)

#### So, with the above parameters, we can get at accuracy of 71%.

#### As it is an unbalanced classification problem, accuracy can't be a good criterion for evaluation. Hence we can stay put with this accuracy score.

In [ ]:
# Now we check overall scores of the entire data set

data.describe()

